from __future__ import annotations

import hashlib
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _sha256(path: Path) -> str | None:
    if not path.is_file():
        return None
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_citations(repo_root: Path) -> dict[str, Any]:
    path = repo_root / "reference" / "citations.json"
    if path.is_file():
        return json.loads(path.read_text())
    return {}


def build_provenance(
    job_id: str,
    *,
    parameters: dict[str, Any],
    reference_dir: Path,
    step_outputs: dict[str, Any],
) -> dict[str, Any]:
    repo_root = reference_dir.parent
    nichenet_dir = reference_dir / "nichenet"
    ref_files = {}
    for p in list(nichenet_dir.rglob("*.csv")) + list(nichenet_dir.rglob("*.rds")):
        ref_files[str(p.relative_to(repo_root))] = _sha256(p)

    return {
        "job_id": job_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "platform": {
            "python": sys.version,
            "system": platform.platform(),
        },
        "parameters": parameters,
        "reference_files_sha256": ref_files,
        "pipeline_steps": step_outputs,
        "citations": _load_citations(repo_root),
    }


def build_methods_text(provenance: dict[str, Any]) -> str:
    cites = provenance.get("citations", {})
    params = provenance.get("parameters", {})
    lines = [
        "Methods (auto-generated by Cell Communication Explorer)",
        "",
        f"Analysis job: {provenance.get('job_id')}",
        f"Generated: {provenance.get('generated_at')}",
        "",
        "Single-cell RNA-seq processing",
    ]

    if "scanpy" in cites:
        s = cites["scanpy"]
        lines.append(f"- Processed with Scanpy ({s['name']}; {s['citation']})")

    if params.get("batch_correction") == "harmony" and "harmony" in cites:
        h = cites["harmony"]
        lines.append(f"- Batch correction: Harmony ({h['citation']})")

    if "celltypist" in cites:
        c = cites["celltypist"]
        model = params.get("celltypist_model", "Immune_All_Low.pkl")
        lines.append(f"- Cell-type annotation: CellTypist model {model} ({c['citation']})")

    comm = params.get("communication_method", "nichenet")
    if comm == "nichenet" and "nichenet" in cites:
        n = cites["nichenet"]
        lines.append(f"- Cell-cell communication: NicheNet ({n['citation']})")
    elif comm == "cellphonedb" and "cellphonedb" in cites:
        cp = cites["cellphonedb"]
        lines.append(f"- Cell-cell communication: CellPhoneDB ({cp['citation']})")

    ref_hashes = provenance.get("reference_files_sha256", {})
    if ref_hashes:
        lines.append("")
        lines.append("Reference data integrity (SHA256):")
        for name, digest in sorted(ref_hashes.items()):
            lines.append(f"- {name}: {digest or 'missing'}")

    lines.append("")
    lines.append(
        "All ligand-receptor hypotheses should be validated experimentally. "
        "Evidence tiers: ESTABLISHED (multiple publications), SUPPORTED (database + expression), "
        "HYPOTHESIS (computational prediction only)."
    )
    return "\n".join(lines)


def write_provenance_bundle(
    output_dir: Path,
    job_id: str,
    *,
    parameters: dict[str, Any],
    reference_dir: Path,
    step_outputs: dict[str, Any],
) -> dict[str, str]:
    prov = build_provenance(
        job_id,
        parameters=parameters,
        reference_dir=reference_dir,
        step_outputs=step_outputs,
    )
    methods = build_methods_text(prov)

    prov_path = output_dir / "provenance.json"
    methods_path = output_dir / "methods.txt"
    prov_path.write_text(json.dumps(prov, indent=2, default=str))
    methods_path.write_text(methods)

    return {"provenance": str(prov_path), "methods": str(methods_path)}
